### ISSUE TITLE
There is no choice apn of several available at the mobile operator.

### ISSUE THREAD

**Issue by RodionD** [schuay/mkwvconf#1]
At the base of the operator may have several access points, usually at different points, different user name and password. In some but they have not only address the point, but the name. It is necessary to make a choice and in this parameter.

**Comment by schuay** [comment]
Could you please provide an example?

**Comment by RodionD** [comment]
/usr/share/mobile-broadband-provider-info/serviceproviders.xml
country code="bg"
provider Vivacom
apn value="internet.vivacom.bg"
name Vivacom Internet (Postpaid)
username vivacom
password>vivacom

apn value="internet.vivatel.bg1"
name Vivatel (old)
username vivatel
password vivatel
dns 192.168.123.123

For example and more in this xml.

Sorry, I do not know how to insert a piece of xml code

**Comment by schuay** [comment]
Thanks. I'm busy at the moment, but I should be able to get back to this in 2 weeks or so.

**Comment by schuay** [comment]
Implemented in 4c0927b01 (and also fixed the PKGBUILD)
